
files <- c("Desktop/Raw data/Pre-Processed data 1/Basketball/run1.csv", "Desktop/Raw data/Pre-Processed data 1/Basketball/run2.csv", "Desktop/Raw data/Pre-Processed data 1/Basketball/run3.csv")
basketball <- list()
for (file in files) {
  basketball[[file]] <- read.csv(file)
}
basketball_all <- do.call(rbind, basketball)
  pv_min <- min(basketball_all$power_voltage_in_volts)
  pc_min <- min(basketball_all$power_current_in_amps)   
  tp_min <- min(basketball_all$TP_round)   
  pv_max <- max(basketball_all$power_voltage_in_volts)   
  pc_max <- max(basketball_all$power_current_in_amps)   
  tp_max <- max(basketball_all$TP_round)   
  pv_mean <- mean(basketball_all$power_voltage_in_volts)   
  pc_mean <- mean(basketball_all$power_current_in_amps)   
  tp_mean <- mean(basketball_all$TP_round)   
  pv_median <- median(basketball_all$power_voltage_in_volts)   
  pc_median <- median(basketball_all$power_current_in_amps)   
  tp_median <- median(basketball_all$TP_round)   
  pv_quantile1 <- quantile(basketball_all$power_voltage_in_volts)   
  pc_quantile3 <- quantile(basketball_all$power_current_in_amps)   
  pv_quantile1 <- quantile(basketball_all$power_voltage_in_volts, 0.25)   
  pc_quantile1 <- quantile(basketball_all$power_current_in_amps, 0.25)   
  tp_quantile1 <- quantile(basketball_all$TP_round, 0.25)   
  tp_quantile3 <- quantile(basketball_all$TP_round, 0.75)   
  pv_quantile3 <- quantile(basketball_all$power_voltage_in_volts, 0.75)   
  pc_quantile3 <- quantile(basketball_all$power_current_in_amps, 0.75)   
  pv_sd <- sd(basketball_all$power_voltage_in_volts)   
  pc_sd <- sd(basketball_all$power_current_in_amps)   
  tp_sd <- sd(basketball_all$TP_round)   
  pv_count <- length(basketball_all$power_voltage_in_volts)   
  pc_count <- length(basketball_all$power_current_in_amps)   
  tp_count <- length(basketball_all$TP_round)   
  files <- c("Desktop/Raw data/Pre-Processed data 1/Gorillatag/run1.csv", "Desktop/Raw data/Pre-Processed data 1/Gorillatag/run2.csv", "Desktop/Raw data/Pre-Processed data 1/Gorillatag/run3.csv")   
  gorillatag <- list()   
  for (file in files)    {   
       gorillatag[[file]] <- read.csv(file)   
      }   
  gorillatag_all <- do.call(rbind, gorillatag)   
  pv_min <- min(gorillatag_all$power_voltage_in_volts)   
  pc_min <- min(gorillatag_all$power_current_in_amps)   
  tp_min <- min(gorillatag_all$TP_round)   
  pv_max <- max(gorillatag_all$power_voltage_in_volts)   
  pc_max <- max(gorillatag_all$power_current_in_amps)   
  tp_max <- max(gorillatag_all$TP_round)   
  pv_mean <- mean(gorillatag_all$power_voltage_in_volts)   
  pc_mean <- mean(gorillatag_all$power_current_in_amps)   
  tp_mean <- mean(gorillatag_all$TP_round)   
  pv_median <- median(gorillatag_all$power_voltage_in_volts)   
  pc_median <- median(gorillatag_all$power_current_in_amps)   
  tp_median <- median(gorillatag_all$TP_round)   
  pv_quantile1 <- quantile(gorillatag_all$power_voltage_in_volts, 0.25)   
  pv_quantile3 <- quantile(gorillatag_all$power_voltage_in_volts, 0.75)   
  pc_quantile1 <- quantile(gorillatag_all$power_current_in_amps, 0.25)   
  pc_quantile3 <- quantile(gorillatag_all$power_current_in_amps, 0.75)   
  tp_quantile1 <- quantile(gorillatag_all$TP_round, 0.25)   
  tp_quantile3 <- quantile(gorillatag_all$TP_round, 0.75)   
     
  pv_sd <- sd(gorillatag_all$power_voltage_in_volts)   
  pc_sd <- sd(gorillatag_all$power_current_in_amps)   
  tp_sd <- sd(gorillatag_all$TP_round)   
     
  pv_count <- length(gorillatag_all$power_voltage_in_volts)   
  pc_count <- length(gorillatag_all$power_current_in_amps)   
  tp_count <- length(gorillatag_all$TP_round)   
     
     
  files <- c("Desktop/Raw data/Pre-Processed data 1/Blaston/run1.csv", "Desktop/Raw data/Pre-Processed data 1/Blaston/run2.csv", "Desktop/Raw data/Pre-Processed data 1/Blaston/run3.csv")   
  Blaston <- list()   
  for (file in files)    {   
       Blaston[[file]] <- read.csv(file)   
      }   
  Blaston_all <- do.call(rbind, Blaston)   
  pv_min <- min(Blaston_all$power_voltage_in_volts)   
  pc_min <- min(Blaston_all$power_current_in_amps)   
  tp_min <- min(Blaston_all$TP_round)   
  pv_max <- max(Blaston_all$power_voltage_in_volts)   
  pc_max <- max(Blaston_all$power_current_in_amps)   
  tp_max <- max(Blaston_all$TP_round)   
  pv_mean <- mean(Blaston_all$power_voltage_in_volts)   
  pc_mean <- mean(Blaston_all$power_current_in_amps)   
  tp_mean <- mean(Blaston_all$TP_round)   
  pv_median <- median(Blaston_all$power_voltage_in_volts)   
  pc_median <- median(Blaston_all$power_current_in_amps)   
  tp_median <- median(Blaston_all$TP_round)   
  pv_quantile1 <- quantile(Blaston_all$power_voltage_in_volts, 0.25)   
  pv_quantile3 <- quantile(Blaston_all$power_voltage_in_volts, 0.75)   
  pc_quantile1 <- quantile(Blaston_all$power_current_in_amps, 0.25)   
  pc_quantile3 <- quantile(Blaston_all$power_current_in_amps, 0.75)   
  tp_quantile1 <- quantile(Blaston_all$TP_round, 0.25)   
  tp_quantile3 <- quantile(Blaston_all$TP_round, 0.75)   
  pv_sd <- sd(Blaston_all$power_voltage_in_volts)   
  pc_sd <- sd(Blaston_all$power_current_in_amps)   
  tp_sd <- sd(Blaston_all$TP_round)   
  pv_count <- length(Blaston_all$power_voltage_in_volts)   
  pc_count <- length(Blaston_all$power_current_in_amps)   
  tp_count <- length(Blaston_all$TP_round)   
     
  files <- c("Desktop/Raw data/Pre-Processed data 1/Innerworld/run1.csv", "Desktop/Raw data/Pre-Processed data 1/Innerworld/run2.csv", "Desktop/Raw data/Pre-Processed data 1/Innerworld/run3.csv")   
  Innerworld <- list()   
  for (file in files)    {   
       Innerworld[[file]] <- read.csv(file)   
      }   
     
  Innerworld_all <- do.call(rbind, Innerworld)   
  pv_min <- min(Innerworld_all$power_voltage_in_volts)   
  pc_min <- min(Innerworld_all$power_current_in_amps)   
  tp_min <- min(Innerworld_all$TP_round)   
  pv_max <- max(Innerworld_all$power_voltage_in_volts)   
  pc_max <- max(Innerworld_all$power_current_in_amps)   
  tp_max <- max(Innerworld_all$TP_round)   
  pv_mean <- mean(Innerworld_all$power_voltage_in_volts)   
  pc_mean <- mean(Innerworld_all$power_current_in_amps)   
  tp_mean <- mean(Innerworld_all$TP_round)   
  pv_median <- median(Innerworld_all$power_voltage_in_volts)   
  pc_median <- median(Innerworld_all$power_current_in_amps)   
  tp_median <- median(Innerworld_all$TP_round)   
  pv_quantile1 <- quantile(Innerworld_all$power_voltage_in_volts, 0.25)   
  pv_quantile3 <- quantile(Innerworld_all$power_voltage_in_volts, 0.75)   
  pc_quantile1 <- quantile(Innerworld_all$power_current_in_amps, 0.25)   
  pc_quantile3 <- quantile(Innerworld_all$power_current_in_amps, 0.75)   
  tp_quantile1 <- quantile(Innerworld_all$TP_round, 0.25)   
  tp_quantile3 <- quantile(Innerworld_all$TP_round, 0.75)   
  pv_sd <- sd(Innerworld_all$power_voltage_in_volts)   
  pc_sd <- sd(Innerworld_all$power_current_in_amps)   
  tp_sd <- sd(Innerworld_all$TP_round)   
  pv_count <- length(Innerworld_all$power_voltage_in_volts)   
  pc_count <- length(Innerworld_all$power_current_in_amps)   
  tp_count <- length(Innerworld_all$TP_round)   
  files <- c("Desktop/Raw data/Pre-Processed data 1/ShapesXR/run1.csv", "Desktop/Raw data/Pre-Processed data 1/ShapesXR/run2.csv", "Desktop/Raw data/Pre-Processed data 1/ShapesXR/run3.csv")   
  ShapesXR <- list()   
  for (file in files)    {   
       ShapesXR[[file]] <- read.csv(file)   
      }   
     
  ShapesXR_all <- do.call(rbind, ShapesXR)   
  pv_min <- min(ShapesXR_all$power_voltage_in_volts)   
  pc_min <- min(ShapesXR_all$power_current_in_amps)   
  tp_min <- min(ShapesXR_all$TP_round)   
  pv_max <- max(ShapesXR_all$power_voltage_in_volts)   
  pc_max <- max(ShapesXR_all$power_current_in_amps)   
  tp_max <- max(ShapesXR_all$TP_round)   
  pv_mean <- mean(ShapesXR_all$power_voltage_in_volts)   
  pc_mean <- mean(ShapesXR_all$power_current_in_amps)   
  tp_mean <- mean(ShapesXR_all$TP_round)   
  pv_median <- median(ShapesXR_all$power_voltage_in_volts)   
  pc_median <- median(ShapesXR_all$power_current_in_amps)   
  tp_median <- median(ShapesXR_all$TP_round)   
  pv_quantile1 <- quantile(ShapesXR_all$power_voltage_in_volts, 0.25)   
  pv_quantile3 <- quantile(ShapesXR_all$power_voltage_in_volts, 0.75)   
  pc_quantile1 <- quantile(ShapesXR_all$power_current_in_amps, 0.25)   
  pc_quantile3 <- quantile(ShapesXR_all$power_current_in_amps, 0.75)   
  tp_quantile1 <- quantile(ShapesXR_all$TP_round, 0.25)   
  tp_quantile3 <- quantile(ShapesXR_all$TP_round, 0.75)   
  pv_sd <- sd(ShapesXR_all$power_voltage_in_volts)   
  pc_sd <- sd(ShapesXR_all$power_current_in_amps)   
  tp_sd <- sd(ShapesXR_all$TP_round)   
  pv_count <- length(ShapesXR_all$power_voltage_in_volts)   
  pc_count <- length(ShapesXR_all$power_current_in_amps)   
  tp_count <- length(ShapesXR_all$TP_round)   
  files <- c("Desktop/Raw data/Pre-Processed data 1/zoe/run1.csv", "Desktop/Raw data/Pre-Processed data 1/zoe/run2.csv", "Desktop/Raw data/Pre-Processed data 1/zoe/run3.csv")   
  zoe <- list()   
  for (file in files)    {   
       zoe[[file]] <- read.csv(file)   
      }   
     
  zoe_all <- do.call(rbind, zoe)   
  pv_min <- min(zoe_all$power_voltage_in_volts)   
  pc_min <- min(zoe_all$power_current_in_amps)   
  tp_min <- min(zoe_all$TP_round)   
  pv_max <- max(zoe_all$power_voltage_in_volts)   
  pc_max <- max(zoe_all$power_current_in_amps)   
  tp_max <- max(zoe_all$TP_round)   
  pv_mean <- mean(zoe_all$power_voltage_in_volts)   
  pc_mean <- mean(zoe_all$power_current_in_amps)   
  tp_mean <- mean(zoe_all$TP_round)   
  pv_median <- median(zoe_all$power_voltage_in_volts)   
  pc_median <- median(zoe_all$power_current_in_amps)   
  tp_median <- median(zoe_all$TP_round)   
  pv_quantile1 <- quantile(zoe_all$power_voltage_in_volts, 0.25)   
  pv_quantile3 <- quantile(zoe_all$power_voltage_in_volts, 0.75)   
  pc_quantile1 <- quantile(zoe_all$power_current_in_amps, 0.25)   
  pc_quantile3 <- quantile(zoe_all$power_current_in_amps, 0.75)   
  tp_quantile1 <- quantile(zoe_all$TP_round, 0.25)   
  tp_quantile3 <- quantile(zoe_all$TP_round, 0.75)   
  pv_sd <- sd(zoe_all$power_voltage_in_volts)   
  pc_sd <- sd(zoe_all$power_current_in_amps)   
  tp_sd <- sd(zoe_all$TP_round)   
  pv_count <- length(zoe_all$power_voltage_in_volts)   
  pc_count <- length(zoe_all$power_current_in_amps)   
  tp_count <- length(zoe_all$TP_round)   
  files <- c("Desktop/Raw data/Pre-Processed data 1/Recroom/run1.csv", "Desktop/Raw data/Pre-Processed data 1/Recroom/run2.csv", "Desktop/Raw data/Pre-Processed data 1/Recroom/run3.csv")   
  Recroom <- list()   
  for (file in files)    {   
       Recroom[[file]] <- read.csv(file)   
      }   
     
  Recroom_all <- do.call(rbind, Recroom)   
  pv_min <- min(Recroom_all$power_voltage_in_volts)   
  pc_min <- min(Recroom_all$power_current_in_amps)   
  tp_min <- min(Recroom_all$TP_round)   
  pv_max <- max(Recroom_all$power_voltage_in_volts)   
  pc_max <- max(Recroom_all$power_current_in_amps)   
  tp_max <- max(Recroom_all$TP_round)   
  pv_mean <- mean(Recroom_all$power_voltage_in_volts)   
  pc_mean <- mean(Recroom_all$power_current_in_amps)   
  tp_mean <- mean(Recroom_all$TP_round)   
  pv_median <- median(Recroom_all$power_voltage_in_volts)   
  pc_median <- median(Recroom_all$power_current_in_amps)   
  tp_median <- median(Recroom_all$TP_round)   
  pv_quantile1 <- quantile(Recroom_all$power_voltage_in_volts, 0.25)   
  pv_quantile3 <- quantile(Recroom_all$power_voltage_in_volts, 0.75)   
  pc_quantile1 <- quantile(Recroom_all$power_current_in_amps, 0.25)   
  pc_quantile3 <- quantile(Recroom_all$power_current_in_amps, 0.75)   
  tp_quantile1 <- quantile(Recroom_all$TP_round, 0.25)   
  tp_quantile3 <- quantile(Recroom_all$TP_round, 0.75)   
  pv_sd <- sd(Recroom_all$power_voltage_in_volts)   
  pc_sd <- sd(Recroom_all$power_current_in_amps)   
  tp_sd <- sd(Recroom_all$TP_round)   
  pv_count <- length(Recroom_all$power_voltage_in_volts)   
  pc_count <- length(Recroom_all$power_current_in_amps)   
  tp_count <- length(Recroom_all$TP_round)   
  files <- c("Desktop/Raw data/Pre-Processed data 1/VRPlayer - tests/run1.csv", "Desktop/Raw data/Pre-Processed data 1/VRPlayer - tests/run2.csv", "Desktop/Raw data/Pre-Processed data 1/VRPlayer - tests/run3.csv")   
  VRPlayer <- list()   
     
  for (file in files)    {   
       VRPlayer[[file]] <- read.csv(file)   
      }   
     
  VRPlayer_all <- do.call(rbind, VRPlayer)   
  pv_min <- min(VRPlayer_all$power_voltage_in_volts)   
  pc_min <- min(VRPlayer_all$power_current_in_amps)   
  tp_min <- min(VRPlayer_all$TP_round)   
  pv_max <- max(VRPlayer_all$power_voltage_in_volts)   
  pc_max <- max(VRPlayer_all$power_current_in_amps)   
  tp_max <- max(VRPlayer_all$TP_round)   
  pv_mean <- mean(VRPlayer_all$power_voltage_in_volts)   
  pc_mean <- mean(VRPlayer_all$power_current_in_amps)   
  tp_mean <- mean(VRPlayer_all$TP_round)   
  pv_median <- median(VRPlayer_all$power_voltage_in_volts)   
  pc_median <- median(VRPlayer_all$power_current_in_amps)   
  tp_median <- median(VRPlayer_all$TP_round)   
  pv_quantile1 <- quantile(VRPlayer_all$power_voltage_in_volts, 0.25)   
  pv_quantile3 <- quantile(VRPlayer_all$power_voltage_in_volts, 0.75)   
  pc_quantile1 <- quantile(VRPlayer_all$power_current_in_amps, 0.25)   
  pc_quantile3 <- quantile(VRPlayer_all$power_current_in_amps, 0.75)   
  tp_quantile1 <- quantile(VRPlayer_all$TP_round, 0.25)   
  tp_quantile3 <- quantile(VRPlayer_all$TP_round, 0.75)   
  pv_sd <- sd(VRPlayer_all$power_voltage_in_volts)   
  pc_sd <- sd(VRPlayer_all$power_current_in_amps)   
  tp_sd <- sd(VRPlayer_all$TP_round)   
  pv_count <- length(VRPlayer_all$power_voltage_in_volts)   
  pc_count <- length(VRPlayer_all$power_current_in_amps)   
  tp_count <- length(VRPlayer_all$TP_round)   
  files <- c("Desktop/Raw data/Pre-Processed data 1/Ultimechs/run1.csv", "Desktop/Raw data/Pre-Processed data 1/Ultimechs/run2.csv", "Desktop/Raw data/Pre-Processed data 1/Ultimechs/run3.csv")   
  Ultimechs <- list()   
     
  for (file in files)    {   
       Ultimechs[[file]] <- read.csv(file)   
      }   
     
  Ultimechs_all <- do.call(rbind, Ultimechs)   
  pv_min <- min(Ultimechs_all$power_voltage_in_volts)   
  pc_min <- min(Ultimechs_all$power_current_in_amps)   
  tp_min <- min(Ultimechs_all$TP_round)   
  pv_max <- max(Ultimechs_all$power_voltage_in_volts)   
  pc_max <- max(Ultimechs_all$power_current_in_amps)   
  tp_max <- max(Ultimechs_all$TP_round)   
  pv_mean <- mean(Ultimechs_all$power_voltage_in_volts)   
  pc_mean <- mean(Ultimechs_all$power_current_in_amps)   
  tp_mean <- mean(Ultimechs_all$TP_round)   
  pv_median <- median(Ultimechs_all$power_voltage_in_volts)   
  pc_median <- median(Ultimechs_all$power_current_in_amps)   
  tp_median <- median(Ultimechs_all$TP_round)   
  pv_quantile1 <- quantile(Ultimechs_all$power_voltage_in_volts, 0.25)   
  pv_quantile3 <- quantile(Ultimechs_all$power_voltage_in_volts, 0.75)   
  pc_quantile1 <- quantile(Ultimechs_all$power_current_in_amps, 0.25)   
  pc_quantile3 <- quantile(Ultimechs_all$power_current_in_amps, 0.75)   
  tp_quantile1 <- quantile(Ultimechs_all$TP_round, 0.25)   
  tp_quantile3 <- quantile(Ultimechs_all$TP_round, 0.75)   
  pv_sd <- sd(Ultimechs_all$power_voltage_in_volts)   
  pc_sd <- sd(Ultimechs_all$power_current_in_amps)   
  tp_sd <- sd(Ultimechs_all$TP_round)   
  pv_count <- length(Ultimechs_all$power_voltage_in_volts)   
  pc_count <- length(Ultimechs_all$power_current_in_amps)   
  tp_count <- length(Ultimechs_all$TP_round)   
 
  